### PR TITLE
Translate frFR.lua strings(Closes issue #20).

### PR DESCRIPTION
**Pull request by beinganonymous**
- Translated strings in ``Locale/frFR.lua``

#20

### CODE REVIEW

**Comment by tilkinsc** [comment]
This PR is a couple commits behind current indev branch, and this file has commands added to it, so you can translate those as necessary. Gonna hold out merging this pr in case you can get to them. Please push to the indev branch rather.

**Comment by beinganonymous** [comment]
Should i commit the changes targetting indev branch or master branch ?

**Comment by tilkinsc** [comment]
Targeting the indev branch, you will have to pull from it to be current with it. Of course I forgot to push the changes as of current, but you keep master clean for easy branch delete methods incase things explode (rather than back tracking commits x_x)

**Comment by beinganonymous** [comment]
Okay, i am closing this PR then.

**Pull request closed without merging**
